### PR TITLE
zuul: build images

### PR DESCRIPTION
**Pull request by berendt**

### CODE REVIEW

**Comment by berendt** [comment]
@osfrickler Is it possible to add dedicated workers with local storage flavors for those jobs?

**Comment by osfrickler** [comment]
Yes, we can define a different label. Which flavor do you want to use?

**Comment by berendt** [comment]
I think the ``SCS-8V-32-100s`` makes sense. This way we also have enough storage + enough VCPUs for more parallel builds.

**Comment by berendt** [comment]
Current test run hangs because of:

```
2023-07-15 12:28:11.499614 | ubuntu-jammy | tee: kolla-build-20230715.log: No space left on device
```

**Comment by berendt** [comment]
Upload will be tested after merge.

**Review by osfrickler — APPROVED** [review]

**Pull request merged**
